version: '2'
services: 
     discovery-service:
                build: ./discovery-service
                container_name: discovery-service
                ports:
                   - 8761:8761
                environment:
                   - EUREKA_INSTANCE_PREFERIPADDRESS=true

     image-downloader:
                build: ./image-downloader
                container_name: image-downloader
                depends_on:
                      - discovery-service
                ports:
                   - 7777:7777
                environment:
                     EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
                     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

     movie-parser:
                build: ./movie-parser
                container_name: movie-parser
                depends_on:
                  - discovery-service
                  - image-downloader
                ports:
                  - 6677:6677
                environment:
                      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
                      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

