version: '2'
services: 
     discovery-service:
                build: ./discovery-service
                container_name: discovery-service
                ports:
                   - 8761:8761
                   - 9010:9010
                environment:
                   - EUREKA_INSTANCE_PREFERIPADDRESS=true

     image-downloader:
                build: ./image-downloader
                container_name: image-downloader
                depends_on:
                      - discovery-service
                ports:
                   - 7777:7777
                   - 9011:9011
                environment:
                     EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
                     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

     tor-proxy:
                image: dperson/torproxy
                container_name: service-proxy

     movie-parser:
                build: ./movie-parser
                container_name: movie-parser
                depends_on:
                  - discovery-service
                  - tor-proxy
                ports:
                  - 6677:6677
                  - 9012:9012
                environment:
                      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
                      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
                      proxy.host: tor-proxy

     movie-data:
                build: ./movie-data
                container_name: movie-data
                depends_on:
                  - discovery-service
                  - movie-parser
                  - image-downloader
                  - mongodb
                ports:
                  - 6655:6655
                  - 9014:9014
                environment:
                      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
                      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
                      spring.data.mongodb.host: mongodb

     mongodb:
                image: mongo:latest
                environment:
                      MONGO_INITDB_ROOT_USERNAME: root
                      MONGO_INITDB_ROOT_PASSWORD: rootpassword
                ports:
                   - 27017:27017
                volumes:
                   - mongodb_data_container:/data/db

     general-parser:
                build: ./general-parser
                container_name: general-parser
                depends_on:
                  - movie-data
                  - movie-parser
                ports:
                  - 6633:6633
                  - 9015:9015
                environment:
                      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
                      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

volumes:
      mongodb_data_container: